### ISSUE TITLE
输入视角问题

### ISSUE THREAD

**Issue by Yangyc07** [ctrasd/gait-view#1]
请问模型每次输入的步态序列的视角是固定的吗，还是序列可以包含不同的视角

**Comment by ctrasd** [comment]
如果是对于同一个序列，那视角是固定的。论文所跑的数据集也都是视角固定的，同一个序列中并没有视角的变化。

**Comment by Yangyc07** [comment]
谢谢你，请问我这样理解对吗，视角矩阵W的维度是（M,  n，D， D）,每一个视角有n个（D, D）维度的矩阵，模型预测出视角之后拿出对应矩阵组（n ，D，D）然后做feature projection。

**Comment by ctrasd** [comment]
可以这么理解。但是注意在CASIA-B上，单纯的加上角度监督是效果最好的。CASIA-B的数据量太小，这样做容易过拟合。

**Comment by dingtao1** [comment]
> 可以这么理解。但是注意在CASIA-B上，单纯的加上角度监督是效果最好的。CASIA-B的数据量太小，这样做容易过拟合。

gaitset在casia-b上训练结果，trans_view的矩阵都是一样的啊。也就是说起作用的是角度的监督loss吗？

**Comment by ctrasd** [comment]
> > 可以这么理解。但是注意在CASIA-B上，单纯的加上角度监督是效果最好的。CASIA-B的数据量太小，这样做容易过拟合。
> 
> gaitset在casia-b上训练结果，trans_view的矩阵都是一样的啊。也就是说起作用的是角度的监督loss吗？

是的，casia-b上最有用的是角度监督loss，oumvlp上是监督与增加不同视角的trans-view共同起作用
